### ISSUE TITLE
How i style selected label

### ISSUE THREAD

**Issue by thakurakhilesh** [RFreij/ngx-mention#2]
Please guide me, How I style selected label like mentionSelect(A function to format the selected item before inserting the text.
) in other packages https://github.com/dmacfarlane/angular-mentions.

**Comment by RFreij** [comment]
Hi,

Sorry for the late reply, I've been busy. 

The feature to format an item before inserting the text wasn't implemented yet. I've just published v1.1.0 that does have the feature. 

The Readme has been updatet with how to use it.
