### ISSUE TITLE
Angular 11 dependency

### ISSUE THREAD

**Issue by SanderVO** [RFreij/ngx-mention#3]
Hello,

Your package works great! I want to update my application to Angular 11, but ngx-mention has a dependency on Angular 9. I get the following warning when I run ng-update:

![image](https://user-images.githubusercontent.com/1046805/101484703-51f85080-395a-11eb-9721-f6afeea47ffe.png)

I can ofcourse run ng-update with the force flag, but it would be nice if this package would be updated to Angular 11.

Thanks.

**Comment by RFreij** [comment]
@SanderVO sorry for the late reply. I completely missed the notification. 

The fix has been published to npm on v1.0.2. The notice shouldn't occur after updating..
