### ISSUE TITLE
Broken demo

### ISSUE THREAD

**Issue by PhiLhoSoft** [RFreij/ngx-mention#4]
Your demo is broken: Firefox says that it blocked .js files because they are served with an "text/html" content type, Chrome just says these files are in 404 status.

BTW, perhaps you could mention how your project differs of the one you forked? Why should we choose it instead of the original one? What are its advantages? Smaller? Simpler? Etc.

**Comment by RFreij** [comment]
Hi @PhiLhoSoft thanks for reaching out. Back when we needed this package angular mentions didnt look actively maintained. It didnt have the selected events or formatting options, so i decided to make one myself. 

I keep it around for when my former colleagues would need an update. I'm not using the package myself so if you need to choose one, take angular mentions, looks more stable now. 

I just saw They've had a couple of releases that added those options we needed as well.
